name: Test Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --amd64 --aarch64 \
            --target cgate-server
