name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish add-on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 --aarch64 \
            --target cgate-server \
            --image "ghcr.io/${{ github.repository_owner }}/{arch}-cgate-server"
